### ISSUE TITLE
Plugin not working with Spyder 5.3.2

### ISSUE THREAD

**Issue by rhkarls** [spyder-ide/spyder.line_profiler#65]
After updating to 5.3.2 (from `conda_forge`) the plugin is not discovered correctly
    
    fromIccProfile: failed minimal tag size sanity
    spyder_line_profiler: cannot import name 'add_pathlist_to_PYTHONPATH' from 'spyder.utils.misc' (C:\Users\rhkarls\Miniconda3\envs\spyder_install\lib\site-packages\spyder\utils\misc.py)
    Traceback (most recent call last):
      File "C:\Users\rhkarls\Miniconda3\envs\spyder_install\lib\site-packages\spyder\app\find_plugins.py", line 67, in find_external_plugins
        mod = importlib.import_module(entry_point.module_name)
      File "C:\Users\rhkarls\Miniconda3\envs\spyder_install\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 843, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\rhkarls\Miniconda3\envs\spyder_install\lib\site-packages\spyder_line_profiler\spyder\plugin.py", line 29, in <module>
        from spyder_line_profiler.spyder.confpage import SpyderLineProfilerConfigPage
      File "C:\Users\rhkarls\Miniconda3\envs\spyder_install\lib\site-packages\spyder_line_profiler\spyder\confpage.py", line 19, in <module>
        from .widgets import SpyderLineProfilerWidget
      File "C:\Users\rhkarls\Miniconda3\envs\spyder_install\lib\site-packages\spyder_line_profiler\spyder\widgets.py", line 37, in <module>
        from spyder.utils.misc import add_pathlist_to_PYTHONPATH, getcwd_or_home
    ImportError: cannot import name 'add_pathlist_to_PYTHONPATH' from 'spyder.utils.misc' (C:\Users\rhkarls\Miniconda3\envs\spyder_install\lib\site-packages\spyder\utils\misc.py)

Perhaps related to changes in this commit https://github.com/spyder-ide/spyder/commit/987453ac66c6000e533dbd1266b610b3fd05388e ?

**Comment by jitseniesen** [comment]
Yes, you are right. The plugin works with Spyder 5.3.1, if you need a workaround.

The function `add_pathlist_to_PYTHONPATH` was removed in spyder-ide/spyder@9400b04aedf3e4d8618c4db36e2c976434a78363 in PR spyder-ide/spyder#17512. It looks like an easy fix.

**Comment by ccordoba12** [comment]
Sorry for the inconvenience @jitseniesen. I hope this will be easy to solve.

**Comment by ccordoba12** [comment]
Sorry for the inconvenience @jitseniesen. I hope this is easy to solve.

**Comment by jitseniesen** [comment]
> Sorry for the inconvenience @jitseniesen. I hope this is easy to solve.

No problem, it's just a one-line change. I should just remember to do a quick test of my plugins when a new Spyder version is about to come out.
